services:
  vnstat-ui:
    container_name: vnstat-ui
    build: .
    volumes:
      - ./data:/var/lib/vnstat:Z
    image: bhoopendrau004/vnstat-ui:latest
    restart: always
    ports:
      - "8090:8000"